name: CI

on: [push]

jobs:
  test:
    name: Node - ${{ matrix.node_version }} OS - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [10, 12]
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Install and Electron Forge make
      run: |
        npm install
        npm run make
    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: ${{ matrix.node_version }}-OS-${{ matrix.os }}
        path: out/make